"""add assets folder and is_registereg and rename note_path to note_file

Revision ID: e7ebd9b5882d
Revises: 34da6f777142
Create Date: 2023-10-30 21:03:25.666097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ebd9b5882d'
down_revision = '34da6f777142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('note_file', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('assets_folder', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('is_registered', sa.Boolean(), nullable=True))
    op.drop_column('users', 'note_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('note_path', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_registered')
    op.drop_column('users', 'assets_folder')
    op.drop_column('users', 'note_file')
    # ### end Alembic commands ###
